site_name: Crypt
#site_url: https://twinredlotus.com
theme:
  name: material
nav:
    - Home: index.md
    - About: about.md
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
